// Compiles the JSON database in /data into a single browser-loadable bundle
// (dashboard/db.js -> window.FH6_DB) so the dashboard runs from file:// with no server.
// Run: node scripts/build-db.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (f) => JSON.parse(readFileSync(join(root, "data", f), "utf8"));

const db = {
  tuningVariables: read("tuning-variables.json"),
  metaCars: read("meta-cars.json"),
  upgradeStrategy: read("upgrade-strategy.json"),
  progression: read("progression.json"),
  rivalsTracks: read("rivals-tracks.json"),
  tuningTemplates: read("tuning-templates.json"),
  eliminatorTips: read("eliminator-tips.json"),
  driftGuide: read("drift-guide.json"),
  tougeGuide: read("touge-guide.json"),
  tuneCodes: read("tune-codes.json"),
  tuneRaw: read("tune-raw.json"),
  tuners: read("tuners.json"),
  ownedCars: read("owned-cars.json"),
  wheelspinCars: read("wheelspin-cars.json"),
  tunerSheets: read("tuner-sheets.json"),
  tunerRoster: read("tuner-roster.json"),
  tuneLab: read("tuning-test-battery.json"),
  partsEffects: read("parts-effects.json"),
  trainingZone: read("training-zone.json"),
  sources: read("sources.json"),
  builtAt: process.env.BUILD_STAMP || "unstamped",
};

const out = `// AUTO-GENERATED by scripts/build-db.mjs — do not edit by hand.\n` +
  `window.FH6_DB = ${JSON.stringify(db, null, 2)};\n`;

writeFileSync(join(root, "dashboard", "db.js"), out);
console.log(`Wrote dashboard/db.js (${db.metaCars.cars.length} cars, ${db.tuningVariables.categories.length} tuning categories, ${db.rivalsTracks.tracks.length} rivals tracks, ${db.tuningTemplates.templates.length} discipline templates, ${db.eliminatorTips.tips.length} eliminator tips)`);
